trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  qaWebAppName: 'devopsDemox'
  releaseWebAppName: 'devopsDemox-prod'
  environmentQA: 'QA'
  environmentRelease: 'Release'
  azureSubscription: 'demo-vn'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: CopyFiles@2
      inputs:
        Contents: '**/*.war'
        TargetFolder: '$(build.artifactstagingdirectory)'
        flattenFolders: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'warfile'
        publishLocation: 'Container'

- stage: DeployQA
  dependsOn: Build
  jobs:
  - deployment: DeployToQA
    displayName: 'Deploy WAR to QA'
    environment: $(environmentQA)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(qaWebAppName)'
              package: '$(Pipeline.Workspace)/warfile/**/*.war'

- stage: DeployRelease
  dependsOn: DeployQA
  jobs:
  - deployment: DeployToRelease
    displayName: 'Deploy WAR to Release'
    environment: $(environmentRelease)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(releaseWebAppName)'
              package: '$(Pipeline.Workspace)/warfile/**/*.war'